USE Falcon_Cyber_Monitoring_System;
CREATE TABLE IF NOT EXISTS Channel (
    `CHANNEL` VARCHAR(128) NOT NULL,
    `NAME` INT(11) UNSIGNED NOT NULL,
    `REG_DATE` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT PK PRIMARY KEY (`CHANNEL`)
);