USE Falcon_Cyber_Monitoring_System;
CREATE TABLE IF NOT EXISTS Signals (
    `CHANNEL` VARCHAR(128) NOT NULL,
    `ID` INT(11) UNSIGNED NOT NULL,
    `FROM_ID` VARCHAR(32) NOT NULL,
    `DATE` int(11) UNSIGNED NOT NULL,
    `MESSAGE` TEXT NOT NULL,
    `VIEWS` int(11) UNSIGNED NOT NULL,
    `EDIT_DATE` int(11) UNSIGNED NOT NULL,
    `SYMBOL_NAME` VARCHAR(64) NOT NULL,
    `SYMBOL_TYPE` VARCHAR(64),
    `SIGNAL_POLARITY` float NOT NULL,
    `PERCENTAGE_CHANGE` float NOT NULL,
    `REG_DATE` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT PK PRIMARY KEY (`CHANNEL`, `ID`, `FROM_ID`)
);