USE Falcon_Cyber_Monitoring_System;
DROP PROCEDURE IF EXISTS DelData;
DELIMITER &&
CREATE PROCEDURE DelData (
    IN `CHANNEL` VARCHAR(128),
    IN `ID` INT(11) UNSIGNED,
    IN `FROM_ID` VARCHAR(32)
    )
BEGIN
    DELETE FROM Data
    WHERE Data.CHANNEL = CHANNEL AND Data.ID = ID AND Data.FROM_ID = FROM_ID;
END &&
DELIMITER ;