crawler:
  endpoint: 'localhost:3001'

analyzer:
  endpoint: 'localhost:3002'

auth:
  roham:
    roham123

session:
  key: 'koa.sess'
  maxAge: 86400000,
  autoCommit: true
  overwrite: true
  httpOnly: true
  signed: true
  rolling: false
  renew: false
  secure: false
  sameSite: null